@startuml

left to right direction

Actor User 
User --> [Web Page]
[Cauldron Controller] 

Interface DaemonCommands

DaemonCommands -- [Cauldron Controller] 

[Web Page] ..> DaemonCommands : use

Actor Cauldron 
[Cauldron Controller]  --> Cauldron

@enduml
